apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - wordpress-deployment.yaml
  - wordpress-service.yaml
  - ingress.yaml
  - nginx-config.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml

secretGenerator:
  - name: monpass
    literals:
      - pass=secret
      - dbname=wordpress
      - user=wpuser
      - rootpass=rootsecret

generatorOptions:
  disableNameSuffixHash: true
